-- Monitor configuration — generated by Monitor Settings on 2026-09-25
-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- List monitors and supported resolutions with: hyprctl monitors all

hl.env("GDK_SCALE", "1")

hl.monitor({ output = "DP-2", mode = "2560x1440@60", position = "0x0", scale = 1 })
hl.monitor({ output = "DP-1", mode = "3840x2160@60", position = "2560x0", scale = 1.5 })
hl.monitor({ output = "HDMI-A-2", mode = "2560x1440@60", position = "5120x0", scale = 1 })
